// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Scaffolded;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(DcaBotContext))]
    [Migration("20250425164224_removing_table_3")]
    partial class removing_table_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Scaffolded.bot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("current_allocation")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("max_price_base_padding_percent")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)");

                    b.Property<decimal>("overall_allowance")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("owner_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "owner_id" }, "Bots_fk1");

                    b.HasIndex(new[] { "id" }, "id")
                        .IsUnique();

                    b.ToTable("bots");
                });

            modelBuilder.Entity("Models.Scaffolded.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email_hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "email_hash" }, "email_hash")
                        .IsUnique();

                    b.HasIndex(new[] { "id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id1");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Models.Scaffolded.bot", b =>
                {
                    b.HasOne("Models.Scaffolded.user", "owner")
                        .WithMany("bots")
                        .HasForeignKey("owner_id")
                        .IsRequired()
                        .HasConstraintName("Bots_fk1");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Models.Scaffolded.user", b =>
                {
                    b.Navigation("bots");
                });
#pragma warning restore 612, 618
        }
    }
}
